internal/controller: support custom atlas.hcl
ariga/atlas-operator pull request #244
Opened 2024-12-11 11:50 UTC by datdao

2024-12-12 10:35 UTC, giautm commented on api/v1alpha1/project_config.go
> +func (s ProjectConfigSpec) GetVars(ctx context.Context, r client.Reader, namespace string) (atlasexec.Vars2, error) {
```suggestion
func (s ProjectConfigSpec) GetVars(ctx context.Context, r client.Reader,  ns string) (atlasexec.Vars2, error) {
```

2024-12-23 05:05 UTC, giautm commented on test/e2e/testscript/custom-config.txtar
> +    }
Write more complicated tests: Use `Getenv`, datasource for load token,

2024-12-31 08:04 UTC, rotemtam commented on README.md
> +> Note: Allowing custom configuration can elevate privileges of the operator. Use this feature with caution.
```suggestion
> Note: Allowing custom configuration enables executing arbitrary commands using the `external` data source as well as arbitrary SQL using the `sql` data source. Use this feature with caution.
```

2024-12-31 08:06 UTC, rotemtam commented on charts/atlas-operator/values.yaml
> +# Warning: This action will elevate the privileges of the operator
```suggestion
# Warning: This setting enables users to use the `external` and `sql` data sources which can be used to execute arbitrary commands and queries. Use with caution. 
```

2025-01-01 14:16 UTC, giautm commented on api/v1alpha1/project_config.go
> +	vars := make(map[string]any)
```suggestion
	var vars atlasexec.Vars2
```

2025-01-01 14:25 UTC, giautm commented on internal/controller/atlasschema_controller.go
> +	}
The check for `EnvName` should check on `s.EnvName`, not `data.EnvName` which always is `defaultEnvName`.

```suggestion
	hasConfig := data.Config != nil
	if hasConfig {
		if !r.allowCustomConfig{
			return nil, errors.New("install the operator with \"--set allowCustomConfig=true\" to use custom atlas.hcl config")
		}
		if s.EnvName == "" {
			return nil, errors.New("env name must be set when using custom atlas.hcl config")
		} else {
			data.EnvName = s
		}
	}
```

2025-01-01 14:53 UTC, giautm requested changes
See my comments

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasschema_controller.go
>  	}
This merge logic isn't correct. Take this test case:


The custom `config` field is set to:
```yaml
spec:
  envName: "test"
  config: |
    variable "db_url" {
      type = string
    }
    variable "dev_db_url" {
      type = string
    }
    env {
      name = atlas.env
      url = var.db_url
      dev = var.dev_db_url
    }
```

Then, the `atlas.hcl` after merge will become:

```hcl
variable "db_url" {
	type = string
}
variable "dev_db_url" {
	type = string
}
env {
	name = atlas.env
	url = var.db_url
	dev = var.dev_db_url
}
env "test" {
	// All generated values
}
```

Expected config has only single unamed `env` block.
```hcl
variable "db_url" {
	type = string
}
variable "dev_db_url" {
	type = string
}
env {
	name = atlas.env
	url = var.db_url
	dev = var.dev_db_url
	// All generated values
}
```

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasschema_controller.go
> +			}
The `lint` config can be provide via global `lint` block, or in the `env` block. This check missing the global case.

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasschema_controller.go
> +		res.SetNotReady("MultipleTargets", "Multiple targets are not supported")
Don't add new reason, because we need document it also keep it alive after added.
```suggestion
		res.SetNotReady("ReadSchema", "Multiple targets are not supported")
```

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasschema_controller.go
> +	if data.URL != nil && data.DevURL == "" {
We don't support DevDB when using custom config right? Then, we need add an error here to report the case to the user.

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasmigration_controller.go
> +	if data.URL != nil && data.DevURL == "" {
The same as `AtlasSchema`

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasmigration_controller.go
> +	}
The same as `AtlasSchema`

2025-01-01 14:53 UTC, giautm commented on internal/controller/atlasmigration_controller.go
> +	}
The same as `AtlasSchema`

2025-01-02 10:03 UTC, giautm commented on internal/controller/atlasschema_controller.go
>  	}
@datdao add test for this case?

2025-01-02 10:07 UTC, datdao commented on internal/controller/atlasschema_controller.go
>  	}
yup, here https://github.com/ariga/atlas-operator/pull/244/commits/9ab327fdf822771f94ec6ce4d75b3b6c608167c6#diff-59d17d058be9091dd756929fde60b55d7fc410959d4f27702b049604d1e738cfR582

2025-01-02 11:25 UTC, giautm commented on internal/controller/atlasmigration_controller.go
> +		if data.URL != nil {
```suggestion
	if !data.hasDevURL() && data.URL != nil {
```

2025-01-03 05:58 UTC, giautm approved these changes

2025-01-05 07:31 UTC, merged